on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    # Install dependencies
    - name: Set up Python 
      uses: actions/setup-python@v7
      with:
        python-version: 3.12

    - name: Install mytoy
      run: |
        # There is a small bug here.
        cd mytoy
        pwd
        pip install --user .

    - name: Run tests
      run: |
        # Another small bug here.
        cd mytoy
        pytest
